In [17]:
from keras.models import load_model
from keras.preprocessing.image import img_to_array
import numpy as np

import glob, re, cv2


In [18]:
model="real_fake.model"
model = load_model(model)

In [19]:
def normalize_image(imagePath):
    image = cv2.imread(imagePath)
    orig = image.copy()
     # pre-process the image for classification
    image = cv2.resize(image, (480, 270))
    image = image.astype("float") / 255.0
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)
    return image

In [20]:
def process_movie(basepath, moviePath):
    movie = re.sub(r'(\.mp4$)', '', moviePath)
    !ffmpeg -i {moviePath} -r 1/1 {movie}%08d.jpg
    imagePaths = glob.glob(movie + "*.jpg")
    images = []
    for path in imagePaths:
        images.append(normalize_image(path))
    return images


In [21]:
def classify_image(model, image):
    # classify the input image
    print("classify_image, ", image)
    exit(0)
    prediction = model.predict(image)
    print("prediction is ", prediction)
    (fake, real) = prediction[0]
     # build the label
    label = "real" if real > fake else "fake"
    proba = real if real > fake else fake
    return label, proba

In [22]:
def classify_all_images(model, images):
    numFake = 0
    fakeProb = 0.0
    numReal = 0
    realProb = 0.0
    for image in images:
        (label, prob) = classify_image(model, image)
        if label == 'real':
            numReal += 1
            realProb += prob
        else:
            numFake += 1
            fakeProb += prob
    
    if numFake > numReal:
        return label, fakeProb / numFake
    else:
        return label, realProb / numReal

In [23]:

def is_movie_fake(movie):
    print("found movie", movie)
    images = process_movie("samples", movie)
    print("found images, ", images)
    return classify_all_images(model, images)

In [24]:
movies = glob.glob('samples/*.mp4')
for movie in movies:
    (label, prob) = is_movie_fake(movie)
    print("movie is ", label, " with probability of ", prob)

found movie samples/syxobtuucp.mp4
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libr

prediction is  [[0. 1.]]
classify_image,  [[[[0.59607846 0.627451   0.6784314 ]
   [0.59607846 0.627451   0.6784314 ]
   [0.59607846 0.627451   0.6784314 ]
   ...
   [0.7019608  0.7529412  0.80784315]
   [0.6862745  0.7372549  0.7921569 ]
   [0.6745098  0.7254902  0.78039217]]

  [[0.5882353  0.61960787 0.67058825]
   [0.5882353  0.61960787 0.67058825]
   [0.5882353  0.61960787 0.67058825]
   ...
   [0.7764706  0.79607844 0.8039216 ]
   [0.8        0.81960785 0.83137256]
   [0.7490196  0.7647059  0.7764706 ]]

  [[0.5803922  0.6039216  0.654902  ]
   [0.5803922  0.6039216  0.654902  ]
   [0.5803922  0.6039216  0.654902  ]
   ...
   [0.7764706  0.8235294  0.8352941 ]
   [0.7529412  0.8        0.80784315]
   [0.77254903 0.8156863  0.8235294 ]]

  ...

  [[0.30588236 0.36862746 0.43137255]
   [0.30588236 0.36862746 0.43137255]
   [0.30588236 0.36862746 0.43137255]
   ...
   [0.81960785 0.8156863  0.83137256]
   [0.81960785 0.8156863  0.83137256]
   [0.81960785 0.8156863  0.83137256]]

  [

prediction is  [[0. 1.]]
classify_image,  [[[[0.61960787 0.627451   0.65882355]
   [0.61960787 0.627451   0.65882355]
   [0.61960787 0.627451   0.65882355]
   ...
   [0.7764706  0.7607843  0.78039217]
   [0.73333335 0.7176471  0.7372549 ]
   [0.7019608  0.6862745  0.7058824 ]]

  [[0.59607846 0.6039216  0.6392157 ]
   [0.6156863  0.627451   0.654902  ]
   [0.6392157  0.64705884 0.6784314 ]
   ...
   [0.78039217 0.7647059  0.78431374]
   [0.8235294  0.80784315 0.827451  ]
   [0.7921569  0.7764706  0.79607844]]

  [[0.60784316 0.6039216  0.6392157 ]
   [0.60784316 0.6039216  0.6392157 ]
   [0.60784316 0.6039216  0.6392157 ]
   ...
   [0.7764706  0.8        0.827451  ]
   [0.7764706  0.8        0.827451  ]
   [0.78039217 0.8039216  0.83137256]]

  ...

  [[0.32941177 0.38431373 0.45882353]
   [0.32941177 0.38431373 0.45882353]
   [0.32941177 0.38431373 0.45882353]
   ...
   [0.8156863  0.80784315 0.85490197]
   [0.8156863  0.80784315 0.85490197]
   [0.8156863  0.80784315 0.85490197]]

  [